apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: 15.0.4
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: monitoring
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-helm-values