apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 1m
  chart:
    spec:
      chart: gateway
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: istio-ingress-helm-values