apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: load-balancing
spec:
  interval: 1m
  chart:
    spec:
      chart: metallb
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: load-balancing
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: metallb-helm-values