apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: library
  namespace: library
spec:
  interval: 1m
  chart:
    spec:
      chart: helm-charts/library
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m