resources:
  - namespace.yaml
  - helmrelease.yaml
patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_USERNAME
          valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DB_USERNAME
    target:
      kind: Deployment
      namespace: library
      name: library
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DB_PASSWORD
    target:
      kind: Deployment
      namespace: library
      name: library