apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  template: 
    spec: 
      containers: 
        - name: library
          env: 
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DB_PASSWORD