replicaCount: 3
ingress:
  enabled: true
  className: istio
  annotations:
    kubernetes.io/ingress.class: istio
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: my-library.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: library
            port:
              number: 8000
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
