replicaCount: 3
ingress:
  enabled: true
  className: "istio"
  hosts:
    - host: my-library.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
