replicaCount: 3
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: my-library.io

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
