replicaCount: 3
ingress:
  enabled: true
  className: istio
  annotations:
    kubernetes.io/ingress.class: istio
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: my-library.io

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
