apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kiali-server
      version: 1.44.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: istio-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: kiali-helm-values